name: Python Static Analysis

on: [pull_request]

jobs:
  scan:
    name: scan
    runs-on: ubuntu-latest
    steps:
      - name: Install MyPy
        run: pip install mypy

      - name: Run MyPy
        run: mypy .
