name: Python Static Analysis

on: [pull_request]

jobs:
  scan:
    name: scan
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.4
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Checkout code
    #   uses: actions/checkout@v3

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'

    # - name: Install dependencies
    #   run: pip install mypy

    # - name: Get list of changed Python files
    #   id: changed-files
    #   run: |
    #     git fetch origin ${{ github.base_ref }} --depth=1
    #     git diff --name-only origin/${{ github.base_ref }} | grep '\.py$' > changed_files.txt

    # - name: Run MyPy on changed files
    #   run: |
    #     if [ -s changed_files.txt ]; then
    #       xargs mypy < changed_files.txt --install-types --non-interactive
    #     else
    #       echo "No Python files were changed."
    #     fi
